SELECT
    CONTAINER_ID,
    COMMODITY,
    ORIGIN,
    DESTINATION,
    TEMPERATURE_C,
    HUMIDITY_PCT,
    VIBRATION_G,
    EVENT_TIMESTAMP,
    INGESTED_AT,

    CASE
        WHEN TEMPERATURE_C > 12 OR HUMIDITY_PCT > 90 THEN 'HIGH'
        WHEN TEMPERATURE_C > 10 OR HUMIDITY_PCT > 85 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ENVIRONMENTAL_RISK

FROM {{ source('raw', 'RAW_IOT_DATA') }}