-- AtmoSync Raw Ingestion Layer DDL
CREATE DATABASE IF NOT EXISTS ATMOSYNC_DB;
CREATE SCHEMA IF NOT EXISTS ATMOSYNC_DB.RAW;

CREATE TABLE IF NOT EXISTS ATMOSYNC_DB.RAW.RAW_IOT_DATA (
    CONTAINER_ID VARCHAR(50),
    COMMODITY VARCHAR(50),
    ORIGIN VARCHAR(100),
    DESTINATION VARCHAR(100),
    TEMPERATURE_C FLOAT,
    HUMIDITY_PCT FLOAT,
    VIBRATION_G FLOAT,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);