-- AtmoSync Optimization Layer
USE DATABASE ATMOSYNC_DB;
USE SCHEMA RAW;

-- Materialized summary for rapid BI dashboard queries
CREATE OR REPLACE MATERIALIZED VIEW MV_CONTAINER_REALTIME_SUMMARY AS
SELECT 
    CONTAINER_ID,
    COMMODITY,
    MAX(EVENT_TIMESTAMP) AS LAST_TELEMETRY_AT,
    AVG(TEMPERATURE_C) AS AVG_TEMP_C,
    AVG(HUMIDITY_PCT) AS AVG_HUMIDITY_PCT
FROM ATMOSYNC_DB.RAW.RAW_IOT_DATA
GROUP BY CONTAINER_ID, COMMODITY;